In [4]:
import os


In [6]:
os.listdir()

['.anaconda',
 '.conda',
 '.condarc',
 '.continuum',
 '.IBM',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.ms-ad',
 '.spss',
 '.virtual_documents',
 '3D Objects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'OneDrive - University of Aberdeen',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled Folder',
 'Videos',
 'Workshop 2 - Next steps in Python programming.ipynb',
 'Workshop_2.ipynb']

In [10]:
os.path.exists("/")

True

In [12]:
help(os)

Help on module os:

NAME
    os - OS routines for NT or Posix depending on what system we're on.

MODULE REFERENCE
    https://docs.python.org/3.11/library/os.html
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This exports:
      - all functions from posix or nt, e.g. unlink, stat, etc.
      - os.path is either posixpath or ntpath
      - os.name is either 'posix' or 'nt'
      - os.curdir is a string representing the current directory (always '.')
      - os.pardir is a string representing the parent directory (always '..')
      - os.sep is the (or a most common) pathname separator ('/' or '\\')
      - os.extsep is the extension separator (always '.')
      - os.altsep is the alternate pathn

In [14]:
help(list.append)

Help on method_descriptor:

append(self, object, /)
    Append object to the end of the list.



In [17]:
import numpy as np
import pandas as pd

In [20]:
myList = ["Mike", "Ellie", "Kim", "Luna"]
myList[0]
# note that Python is a 0-based language

'Mike'

In [23]:
myList[1:3]
# note that index 3 is NOT included and the '1' index is the 2nd element because Python starts counting at 0!

['Ellie', 'Kim']

In [30]:
myList[::2] # the first 2 indices are empty, which just defaults to the first and last

['Mike', 'Kim']

In [39]:
myList[-1]
#last element from the end

'Luna'

In [41]:
myList[::-1]
#reverse

['Luna', 'Kim', 'Ellie', 'Mike']

In [43]:
myList[::-2]
#reverse, but gives everz second value

['Luna', 'Ellie']

In [45]:
myList[:-1]

['Mike', 'Ellie', 'Kim']

In [47]:
myList[::]

['Mike', 'Ellie', 'Kim', 'Luna']

In [51]:
print (myList)

['Mike', 'Ellie', 'Kim', 'Luna']


In [53]:
myList[::-3]

['Luna', 'Mike']

In [61]:
dna_seqs = ['ATGGGACTGCCCTTGATGCCTCACGTATCCAAAAGCGTATCATGGAGCACTCGGAAACGCACTATAGCAATACCAGACCGTGATATACAACCAGATCACTCTACGATTAAACGACTGCGCCGCCGTATTGCGCTGCTTATCCGAGAAGCAGTCCCTCGTGCGACGCAGCACCAAGAACAAGTCTCAGAGTACCTTTGGACGTATGACTTCAGGATCGAGTCGGCGGCTAGGTTCTATGGGGAGCTCCGTGATAGGTCATCTAGACAGGGTGTGTATTATTTGAGAGTAAAACGAAATCCTCCTCGCATGTACGGGTCAATGGAATTCCCGGTCAGA',
            'ATGGACACCTGGACATACTCCCAAGAGGCTGGAGCAGTGCCCCATTCCTCGGTGCCTCAAGTTCTGGGAATGTGCAATCCTCCGCGAGACATTCAAGGTTTCAGACCACGCGATCGGGTTAAGATACTATCTCAAGTACTTCTTTCGTGTAAGGCACCACTAGAATTGCTTACTTATCCAGGCGGACAAACTGCAATCCTATCTTCATGGGGGGTAGATTTACCATTTTGTAAGAATCTAGACGCACCACGTGGGCGTAGCGACAGGGAGACACAATGGAGCTGCATGATATGGCGGGATCCAAGATCCATGGCGAGCGCGTCATACTTTAGGTGC',
            'ATGGTGCGCACGATTGAGTTGGAATTAGTCCCCAGACTGGCGACCATTACATACACCCTCCACCTTCCACGTCGGTTCAGCACGGGGTGGTGTTTCTCTCCAACACGAGGCCCGGGCGAATTAGTATTGATAATGCCTGGGCAGACAGCACTGGCCCGGCAGGAGATACTGGGCGATGGAAGACGTGGGTTAAGGCACGTCGGTTCTCTAGGTTTTCTATACTGGGCACGGAAGTTAGGGGCTAAAGAGCAACATACCTCTCCGCTGTCGGTCGATAGTGAGTCTTGCATAGCGATTGCTAAGAGCCTAGTTAAGCATACTCGTAACCGCGCCGCG',
            'ATGCCTCCCGGTATCGCTGAGGCCCTAGCAAACGCACAGATCAACCAACTTGTGTCTAACGCCATGGGATCTGCCGCATTAGCTAACAATATTACGCCTATAACGCACGGCTTACCTTTCAAATGTGCTGACCAAGTGGCCTCGATACAATTAGGGACTACAGGGGATAGATGTGCAAGTTTGTTTCTATCAGCGCCGGTGATTCTACGACCGTGTAATCAGAGGGCAGCGAAGATGGATAAGGGGTTGACCAACATGCTCAGTAATGATCCAGGAGCCGGTTATGCCATGCGAATATGCATGTGCACAGTAGCCGGGAGAGCTTGTATTCGTATA',
            'ATGACCCCACGCGGACCGTCAGGAGAAATCCTCTCACGGGATCCCGTCACTGTAACGCTCAGGGTCTTACGGCAACTCGAATGCTGTCGAAAATGTGGCAGTCAATCTCTATACCGGGGTCCGAGCTTTTTACATGTAATTTTGCAAGAATTCTTATATAGCACGATGAGACACGTACCCGATCACTTCGCCCAGCATACACTGATTAATACCGTCTATGTGATGTATTTACTTAAGACTCTCGCAACACCCGTGGCTTGGCGAAGTCTATCTGCACTAGTCGGGTCAGCCGTGCGGCGCGCACACACATCAAAGTGGCCGCAGTTGAGCGCAGTG']


In [70]:
len(dna_seqs[0])
#Length of the first string

336

In [73]:
dna_array = np.ndarray((5, 5, 336))
dna_array

array([[[8.95370516e-312, 8.95348573e-312, 8.39911598e-323, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.000000

In [77]:
dna_array = np.zeros((5, 5, 336))
dna_array
#zeros will fill in the matrix with zeros

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [79]:
dna_array.shape
#attribute to tell me how big it is

(5, 5, 336)

In [82]:
for idx1 in range(len(dna_seqs)):
    # loop 1 gets each seq
    # loop 2 gets the other seq to compare to.
    seq1 = dna_seqs[idx1]
    for idx2 in range(len(dna_seqs)):
        seq2 = dna_seqs[idx2]
        # assume the sequences are the same length
        for nt in range(len(seq1)):
            if seq1[nt] == seq2[nt]:
                dna_array[idx1, idx2, nt] = 1
            else:
                dna_array[idx1, idx2, nt] = 0 # we don't actually need this because the default value is already 0

In [84]:
print(dna_array)

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 0. 1. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 0. 1.]
  [1. 1. 1. ... 0. 0. 0.]]

 [[1. 1. 1. ... 0. 1. 0.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]]

 [[1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 0. 1.]]

 [[1. 1. 1. ... 1. 0. 1.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 0. 1. 0.]]

 [[1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 0. 1.]
  [1. 1. 1. ... 0. 1. 0.]
  [1. 1. 1. ... 1. 1. 1.]]]


In [89]:
dna_array[0, 0, :] # sequence 1 matches perfectly to itself


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [92]:
dna_array[0, 4, :] #compare sequence 1 and 4

array([1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
       0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [102]:
np.sum(dna_array[1, 1, :]) # compares how many nucleotides are the same between sequence 1 and 1


336.0

In [104]:
np.sum(dna_array[1, 4, :]) # compares how many nucleotides are the same between sequence 1 and 4

97.0

In [108]:
np.sum(dna_array, 0) #compares rows

array([[5., 5., 5., ..., 2., 2., 2.],
       [5., 5., 5., ..., 1., 2., 1.],
       [5., 5., 5., ..., 2., 1., 2.],
       [5., 5., 5., ..., 2., 2., 2.],
       [5., 5., 5., ..., 2., 2., 2.]])

In [110]:
np.sum(dna_array, 1) #compares colums

array([[5., 5., 5., ..., 2., 2., 2.],
       [5., 5., 5., ..., 1., 2., 1.],
       [5., 5., 5., ..., 2., 1., 2.],
       [5., 5., 5., ..., 2., 2., 2.],
       [5., 5., 5., ..., 2., 2., 2.]])

In [122]:
np.sum(dna_array, 2) #compares all, third dimension

array([[336.,  90.,  98.,  85.,  94.],
       [ 90., 336.,  90.,  94.,  97.],
       [ 98.,  90., 336.,  94.,  84.],
       [ 85.,  94.,  94., 336.,  87.],
       [ 94.,  97.,  84.,  87., 336.]])

In [124]:
np.sum(dna_array[:,:,99], 1) #how many sequences matches at 99th

array([2., 2., 1., 2., 2.])

In [127]:
phone_book = {"Names": ["Mike", "Daniel", "Ellie", "Heather"],
             "Office": ["6.17", "5.23", "3.20", "3.18"],
             "Department": ["Immunology", "Neuroscience", "Developmental Biology", "Immunology"]}
pb_df = pd.DataFrame(phone_book)

In [129]:
pb_df

Names Office             Department
0     Mike   6.17             Immunology
1   Daniel   5.23           Neuroscience
2    Ellie   3.20  Developmental Biology
3  Heather   3.18             Immunology

In [131]:
pb_df.shape

(4, 3)

In [135]:
pb_df.set_index("Names")

Office             Department
Names                                
Mike      6.17             Immunology
Daniel    5.23           Neuroscience
Ellie     3.20  Developmental Biology
Heather   3.18             Immunology

In [137]:
pb_df.shape

(4, 3)

In [149]:
pb_df.iloc[0, :]

Names               Mike
Office              6.17
Department    Immunology
Name: 0, dtype: object

In [152]:
pb_df["Names"]

0       Mike
1     Daniel
2      Ellie
3    Heather
Name: Names, dtype: object

In [155]:
pb_df.set_index("Names", inplace=True, drop=False)
pb_df

Names Office             Department
Names                                         
Mike        Mike   6.17             Immunology
Daniel    Daniel   5.23           Neuroscience
Ellie      Ellie   3.20  Developmental Biology
Heather  Heather   3.18             Immunology

In [158]:
import re

In [161]:
# we make our regex then convert it into a regex object using re.compile
tata_re = re.compile("TATA[A|T]A[A|T]")
tata_re

re.compile(r'TATA[A|T]A[A|T]', re.UNICODE)

In [164]:
bact_seq = "CACTTCAGGTTAAGCGGCGCGGCCTGCGCATTTTGGATATATATAATCCT"
tata_match = tata_re.search(bact_seq)
tata_match

<re.Match object; span=(37, 44), match='TATATAT'>